agent:
  uri: "http://localhost:9000/data"

resilience4j:
  circuitbreaker:
    configs:
      default:
        # slding window
        slidingWindowType: COUNT_BASED  #?? ? ??? ??? ???? ??? ??
        slidingWindowSize: 10 #???? ??? ??

        # fail
        failureRateThreshold: 20  #??? ??? ?? ?? (?? ? / ???? ??? ??)
        minimumNumberOfCalls: 5  #??? ???? ?? ?? ?? ? (???? ???? ? ??? ???? ???? ?? ??)

        # delay
        slowCallRateThreshold: 10  #??? ??? ?? ?? (?? ? / ???? ??? ??)
        slowCallDurationThreshold: 3000  #???? ??? ??

        # half-open
        permittedNumberOfCallsInHalfOpenState: 10 #half open ???? ?? ??? ???? ?? ?? ?
        maxWaitDurationInHalfOpenState: 0  #half open ?? ?? ?? (?? 0?? ??? ??? ? ?? ?? ? ?? ??? ??)
        waitDurationInOpenState: 60000  #open ???? half open?? ???? ???? ??
        automatic-transition-from-open-to-half-open-enabled: true #open ???? half open ?? ?? ?? (true? ?? ??? ?? ? ?? ??)
        register-health-indicator: true #?? ?? ?? (actuator?)

        # ?? ?? (?? ?? ?? ??? ????? ??? ???? ??? ???? ?? ?)
        record-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
    instances:
      localAgentCircuitBreaker:
        baseConfig: default

